files:
  - Hjson
  - Java

Hjson: |+2
  ```
  {
    tables: [{
        name: PlayerStatsView
        extend: PlayerStats
        description:
        '''
        A long description
        '''
        category: Sports
        cardinality : large
        filterTemplate : createdOn>={{start}};createdOn<{{end}}
        isFact : true
        tags: ['Game', 'Player']
        measures : [
            {
            name : lowScore
            type : INTEGER
            definition: 'MIN({{highScore}})'
            }
        ],
        dimensions : [
            {
                name : createdOn
                type : TIME
                definition : '{{created_on}}'
                grain:
                {
                    # Change Type from SIMPLEDATE to WEEK
                    type :  WEEK
                    sql :  '''
                    PARSEDATETIME(FORMATDATETIME({{}}, 'yyyy-MM-dd'), 'yyyy-MM-dd')
                    '''
                }
            }
        ]
    }]
  }
  ```

Java: |+2
  ```java
  @Include
  @VersionQuery(sql = "SELECT COUNT(*) from playerStats")
  @EqualsAndHashCode
  @ToString
  @TableMeta(description = "A long description", category = "Sports", tags = {"Game", "Player"}, filterTemplate = "createdOn>={{start}};createdOn<{{end}}", size = CardinalitySize.LARGE)
  public class PlayerStatsExtends extends PlayerStats {

      // Only Adding New Attribue, can use extends.
      @MetricFormula("MIN({{highScore}})")
      private long lowScore;
  }

  @Include
  @VersionQuery(sql = "SELECT COUNT(*) from playerStats")
  @EqualsAndHashCode
  @ToString
  @TableMeta(description = "A long description", category = "Sports", tags = {"Game", "Player"}, filterTemplate = "createdOn>={{start}};createdOn<{{end}}", size = CardinalitySize.LARGE)
  public class PlayerStatsChangeType {

      public static final String DATE_FORMAT = "PARSEDATETIME(FORMATDATETIME({{}}, 'yyyy-MM-dd'), 'yyyy-MM-dd')";
      public static final String YEAR_MONTH_FORMAT = "PARSEDATETIME(FORMATDATETIME({{}}, 'yyyy-MM'), 'yyyy-MM')";

      @Id
      private String id;

      @MetricFormula("MAX({{highScore}})")
      @ColumnMeta(friendlyName = "High Score")
      private long highScore;

      @ColumnMeta(size = CardinalitySize.LARGE)
      private String name;

      @Join("{{country_id}} = {{playerCountry.id}}", type = JoinType.LEFT)
      private Country playerCountry;

      @DimensionFormula("{{playerCountry.isoCode}}")
      @ColumnMeta(friendlyName = "Country Code")
      private String countryCode;

      @Temporal(grain = @TimeGrainDefinition(grain = TimeGrain.YEAR_MONTH, expression = YEAR_MONTH_FORMAT), timeZone = "UTC")
      @DimensionFormula("{{updated_on}}")
      private YearMonth updatedOn;

      // Change Type from SIMPLEDATE to WEEK
      @Temporal(grain = @TimeGrainDefinition(grain = TimeGrain.WEEK, expression = DATE_FORMAT), timeZone = "UTC")
      @DimensionFormula("{{created_on}}")
      private SimpleDate createdOn;

      // New Column Added
      @MetricFormula("MIN({{highScore}})")
      private long lowScore;
  }
  ```
