files:
  - Spring
  - Elide Standalone

Spring: |+2
  ```yaml
  elide:
    async:
      threadPoolSize: 10
      maxRunTimeMinutes: 120
      queryCleanupDays: 10
      queryCancellationIntervalSeconds: 600
      maxAsyncAfterSeconds: 30
  ```

Elide Standalone: |+2
  ```java
  @Override
  public ElideStandaloneAsyncSettings getAsyncProperties() {
      ElideStandaloneAsyncSettings asyncProperties = new ElideStandaloneAsyncSettings() {
          @Override
          default Integer getThreadSize() {
              return 10;
          }

          @Override
          default Integer getMaxRunTimeSeconds() {
              return 120;
          }

          @Override
          default Integer getQueryCleanupDays() {
              return 10;
          }

         @Override
         default Integer getQueryCancelCheckIntervalSeconds() {
             return 600;
         }

        @Override
        default Integer getMaxAsyncAfterSeconds() {
            return 30;
        }
      }
      return asyncProperties;
  }
  ```
