# jekyll configuration
markdown: redcarpet
exclude: ["README.md"]
highlighter: pygments

# site-specific configuration
BASE_PATH: https://git.corp.yahoo.com/pages/railsplitter/elide-doc
ASSET_PATH: /assets
